"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { governancePolicy, primaryResource, resourceLedgerState, resourceRequiresWholeUnits, type WorkspaceData } from "../lib/domain";
import { requestInboxView, type AgentRequestInput, type InboxView } from "../lib/request-inbox";
import { GitHubNotificationStatus, useGitHubNotifications } from "./github-notification-status";

const labels: Record<string, string> = { pending_approval: "Ready for your decision", waiting_for_budget: "Waiting for budget", needs_review: "Eligibility review", blocked: "Policy blocked", needs_verification: "Verify connected evidence", approved: "Budget authorized", rejected: "Declined", succeeded: "Action completed", failed: "Action failed", cancelled: "Approval revoked", stale: "Authorization needs review" };
type Row = InboxView["rows"][number];
type Decision = { request_id: string; decision: "approve" | "reject"; review_fingerprint: string; rationale: string };
interface Props {
  data: WorkspaceData;
  signedIn: boolean;
  busy: boolean;
  error: string;
  onConnect: () => void;
  onReceive: (requests: AgentRequestInput[]) => Promise<unknown>;
  onDecide: (decision: Decision) => Promise<void>;
  onRefresh: () => Promise<void>;
  onVerify: (id: string) => Promise<void>;
  onAction: (id: string) => void;
}
export function RequestInbox({ data, signedIn, busy, error, onConnect, onReceive, onDecide, onRefresh, onVerify, onAction }: Props) {
  const notifications = useGitHubNotifications(signedIn, data);
  const [view, setView] = useState<InboxView | null>(null);
  const [filter, setFilter] = useState("all");
  const [review, setReview] = useState<{ row: Row; fingerprint: string } | null>(null);
  useEffect(() => { let active = true; void requestInboxView(data).then((result) => { if (active) setView(result); }); return () => { active = false; }; }, [data]);
  const resource = primaryResource(data.policy), ledger = resourceLedgerState(resource, data.ledger);
  const rows = view?.rows ?? [];
  const attention = rows.filter((row) => ["pending_approval", "needs_verification", "needs_review", "blocked", "stale", "failed", "cancelled"].includes(row.status));
  const shown = rows.filter((row) => filter === "all" || filter === "attention" && attention.includes(row) || filter === "waiting" && row.status === "waiting_for_budget" || filter === "authorized" && ["approved", "succeeded"].includes(row.status));
  const percent = (amount: number) => `${Math.min(100, Math.max(0, amount / Math.max(resource.capacity, 1) * 100))}%`;
  return <div className="request-inbox">
    <section className="inbox-budget" aria-label="Shared budget">
      <div><span className="eyebrow">One shared budget</span><h2>{resource.label}</h2><p>{resource.capacity.toLocaleString()} {resource.unit} configured · {ledger.policyReserve.toLocaleString()} protected</p><div className="inbox-budget-track" aria-label={`${ledger.available.toLocaleString()} ${resource.unit} available`}><span style={{ width: percent(ledger.committed + ledger.consumed) }} /><span className="reserved" style={{ width: percent(ledger.reserved) }} /><span className="protected" style={{ width: percent(ledger.policyReserve) }} /></div></div>
      <div><span>Available to authorize</span><strong>{ledger.available.toLocaleString()} <small>{resource.unit}</small></strong><p>Uncommitted capacity</p></div>
      <div><span>Already reserved</span><strong>{ledger.reserved.toLocaleString()} <small>{resource.unit}</small></strong><p>{(ledger.committed + ledger.consumed).toLocaleString()} committed or consumed</p></div>
    </section>
    <div className="inbox-flow"><span>01 <b>Agents request</b></span><span>02 <b>Policy compares</b></span><span>03 <b>{governancePolicy(data.policy).requireApproval ? "You authorize" : "Policy authorizes"}</b></span><span>04 <b>Budget is reserved</b></span></div>
    <section className="inbox-queue" aria-label="Incoming agent requests">
      <div className="inbox-toolbar"><div><span className="eyebrow">Across your agents</span><h2>Incoming requests <span className="inbox-count">{rows.length}</span></h2><p>{signedIn ? "New deliveries appear while this inbox is open." : "Local workspace · sign in to receive requests from external agents."}</p></div><div className="inbox-toolbar-actions"><button type="button" className="button secondary" disabled={busy || !signedIn} onClick={() => void onRefresh()}>Refresh inbox</button><button type="button" className="button primary" onClick={onConnect}>Connect agents</button></div></div>
      {error && <p className="form-error" role="alert">{error}</p>}
      {notifications.error && <p className="form-error" role="alert">{notifications.error}</p>}
      {view?.blockers.length ? <p className="inbox-notice" role="status">{view.blockers.join(" ")}</p> : null}
      {rows.length > 0 && <div className="inbox-filters" role="group" aria-label="Filter incoming requests">{[["all", `All requests ${rows.length}`], ["attention", `Needs attention ${attention.length}`], ["waiting", "Waiting for budget"], ["authorized", "Authorized"]].map(([id, label]) => <button key={id} type="button" aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div>}
      {!view ? <p role="status">Evaluating the shared portfolio…</p> : !rows.length ? <div className="inbox-empty"><span className="inbox-empty-mark" aria-hidden="true">↓</span><h3>Let the requests come to you.</h3><p>Agents send what they need and why. RuleRipple compares their requests against one shared policy. No repository or source URL is required.</p><button className="button secondary" type="button" onClick={onConnect}>Set up request intake</button>{data.cases.length > 0 && <small>{data.cases.length} existing requests remain in All requests and still count toward the portfolio.</small>}</div> : !shown.length ? <p className="inbox-empty">No requests in this view.</p> : <div className="inbox-cards">{shown.map((row) => <article className={`inbox-request ${row.status === "waiting_for_budget" ? "is-waiting" : ""}`} key={row.requestId}>
        <div className="inbox-request-head"><span className="inbox-agent-avatar" aria-hidden="true">{row.agent.name.slice(0, 2).toUpperCase()}</span><div><strong>{row.agent.name}</strong><small>Received {new Date(row.receivedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</small></div><span className={`inbox-state ${row.status}`}>{row.settled ? "Usage reconciled" : row.executionId && row.status === "pending_approval" ? "Action awaiting approval" : labels[row.status] ?? row.status}</span></div>
        <h3>{row.name}</h3><p className="inbox-request-reason">{row.reason}</p>
        <div className="inbox-amounts"><div><span>Requested</span><strong>{row.requested.toLocaleString()} <small>{row.unit}</small></strong><small>Minimum useful: {row.minimum.toLocaleString()}</small></div><div><span>{row.settled ? "Original authorization" : row.authorized > 0 ? "Budget authorized" : row.prepared > 0 ? "Prepared · not authorized" : "Policy can authorize"}</span><strong>{(row.authorized || row.prepared || row.proposed).toLocaleString()} <small>{row.unit}</small></strong><small>Policy rank {row.rank ?? "—"} · {data.policy.outcomes[row.outcome]}</small></div></div>
        <p className="inbox-explanation">{row.explanation}</p>{row.authorized > 0 && <p className="inbox-accounting"><strong>{row.accounting.remainingAuthorization.toLocaleString()} {row.unit}</strong> remaining authorization · <strong>{row.accounting.consumed.toLocaleString()}</strong> recorded usage{row.settled && <span> · Request settled; additional work needs a new request.</span>}</p>}
        {signedIn && row.status === "approved" && !row.executionId && row.source.system === "github" && /^[a-f0-9-]{36}$/.test(row.agent.id) && <GitHubNotificationStatus requestId={row.requestId} settled={row.settled} state={notifications} />}
        <details className="inbox-evidence"><summary>Why this decision?</summary><p>Simulation: {row.simulated.toLocaleString()} {row.unit}. Available authorization also accounts for current commitments and higher-ranked requests.</p>{row.trace.map((step, index) => <p key={`${step.ruleId}-${index}`}><strong>{step.label}</strong> · {step.message}</p>)}<p>Submitted agent ID: {row.agent.id}. Identity and policy signals are supplied by the workspace-authorized caller.</p><p>Source: {row.source.system} · {row.source.externalId} {row.source.url && <a href={row.source.url} target="_blank" rel="noreferrer">Open source ↗</a>}</p></details>
        <div className="inbox-card-actions">{row.executionId ? <><button type="button" className="button primary" disabled={busy} onClick={() => onAction(row.executionId!)}>{row.status === "pending_approval" || row.status === "stale" ? "Review external action" : "View action history"}</button>{["rejected", "cancelled", "failed"].includes(row.status) && row.adapter && <button type="button" className="button secondary" disabled={busy || !signedIn || row.proposed <= 0} onClick={() => void onVerify(row.requestId)}>Verify evidence again</button>}</> : row.adapter ? <><button type="button" className="button primary" disabled={busy || !signedIn || row.status !== "needs_verification"} onClick={() => void onVerify(row.requestId)}>Verify evidence & prepare action</button><small>{view.approvalRequired ? "No execution until you approve." : "Verified, funded actions run automatically under this policy."}</small></> : !["approved", "rejected"].includes(row.status) ? <button type="button" className="button primary" disabled={busy} onClick={() => setReview({ row, fingerprint: view.reviewFingerprint })}>Review allocation</button> : <small>{row.status === "approved" ? "Authorization recorded. Usage is accounted for separately." : "Decision retained in the audit history."}</small>}</div>
      </article>)}</div>}
      {rows.length > 0 && <p className="form-note">Every request is evaluated alongside all {view?.portfolioCount} active portfolio requests. New arrivals never silently take back an existing authorization.</p>}
    </section>
    <details className="inbox-manual"><summary>Enter a request on behalf of an agent</summary><p>For an occasional manual request. Connected agents use the same intake contract automatically.</p><ManualRequest data={data} busy={busy} onReceive={onReceive} /></details>
    {review && <AllocationReview row={review.row} stale={view?.reviewFingerprint !== review.fingerprint} busy={busy} error={error} onClose={() => setReview(null)} onDecide={async (decision, rationale) => { await onDecide({ request_id: review.row.requestId, decision, rationale, review_fingerprint: review.fingerprint }); setReview(null); }} />}
  </div>;
}

export function IntakeContract({ data }: { data: WorkspaceData }) {
  const [copied, setCopied] = useState(false);
  const resource = primaryResource(data.policy);
  const template = { requests: [{ submission_id: "<retry-safe ID, up to 100 characters>", source: { system: "<system identifier>", external_id: "<source request ID>" }, name: "<request title>", reason: "<why additional capacity is needed>", resource_id: resource.id, requested: null, minimum: null, values: Object.fromEntries(data.policy.fields.map((field) => [field.key, null])) }] };
  return <section className="inbox-contract"><div><span className="eyebrow">Incoming requests</span><h3>One request contract. Any agent.</h3><p>Send a typed budget request from your workflow. Intake authenticates the workspace, prevents duplicate deliveries, and evaluates the full portfolio. It never accepts a caller-supplied approval.</p></div><div className="inbox-contract-methods"><article><b>HTTPS intake</b><code>POST /api/agent-requests</code><p>Create a scoped connection above. Send its credential as Authorization: Bearer, stored only in your worker’s secret store. Identity comes from the connection.</p><code>GET /api/agent-requests?request_id=…</code><p>Read the decision before using the authorized budget.</p></article><article><b>Browser agents</b><code>submit_budget_requests</code><p>Use WebMCP in the signed-in workspace. The same validation, shared budget and approval rules apply.</p></article></div><details><summary>Request schema for this policy</summary><p>Replace every placeholder and null with your request’s actual values. Source is provenance, not a claim that a connector is installed.</p><ul className="inbox-field-schema">{data.policy.fields.map((field) => <li key={field.key}><code>{field.key}</code> — {field.label}: {field.type}{field.type === "boolean" ? " (true or false)" : field.type === "enum" ? ` (${field.options?.join(", ")})` : `${field.min === undefined ? "" : ` · minimum ${field.min}`}${field.max === undefined ? "" : ` · maximum ${field.max}`}`}</li>)}</ul><p>Resource: {resource.id} · {resourceRequiresWholeUnits(resource) ? "whole" : "fractional"} {resource.unit}. Minimum useful amount cannot exceed the requested amount.</p><pre>{JSON.stringify(template, null, 2)}</pre><button type="button" className="button secondary" onClick={async () => { try { await navigator.clipboard.writeText(JSON.stringify(template, null, 2)); setCopied(true); } catch { setCopied(false); } }}>{copied ? "Copied" : "Copy request template"}</button></details><p className="form-note">Each connection is limited to one source and resource. Revoke it here to stop access. Proposed allocation is not approval; the worker must read its recorded decision.</p></section>;
}

function ManualRequest({ data, busy, onReceive }: Pick<Props, "data" | "busy" | "onReceive">) {
  const [message, setMessage] = useState("");
  const delivery = useRef<{ id: string; payload: string } | null>(null);
  const resource = primaryResource(data.policy);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const element = event.currentTarget, form = new FormData(element); setMessage("");
    const payload = JSON.stringify([data.policy, [...form.entries()]]);
    if (!delivery.current || delivery.current.payload !== payload) delivery.current = { id: crypto.randomUUID(), payload };
    const id = delivery.current.id;
    const values = Object.fromEntries(data.policy.fields.map((field) => { const raw = String(form.get(`value:${field.key}`)); return [field.key, field.type === "boolean" ? raw === "true" : field.type === "number" || field.type === "integer" ? Number(raw) : raw]; }));
    try { await onReceive([{ submission_id: id, agent: { id: String(form.get("agentId")), name: String(form.get("agentName")) }, source: { system: "manual", external_id: id }, name: String(form.get("name")), reason: String(form.get("reason")), resource_id: resource.id, requested: Number(form.get("requested")), minimum: Number(form.get("minimum")), values }]); delivery.current = null; element.reset(); setMessage("Request received. Review its allocation in the inbox above."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Request could not be received."); }
  }
  return <form className="inbox-intake-form" onSubmit={submit}><fieldset disabled={busy}><div className="inbox-form-grid"><label>Agent name<input name="agentName" required maxLength={80} /></label><label>Agent identifier<input name="agentId" required maxLength={80} /></label><label className="full">Request title<input name="name" required maxLength={100} /></label><label className="full">Why is more budget needed?<textarea name="reason" required maxLength={500} rows={2} /></label><label>Requested ({resource.unit})<input name="requested" type="number" required min={resourceRequiresWholeUnits(resource) ? 1 : 0.000001} max={100000000} step={resourceRequiresWholeUnits(resource) ? 1 : "any"} /></label><label>Minimum useful amount ({resource.unit})<input name="minimum" type="number" required min={0} max={100000000} step={resourceRequiresWholeUnits(resource) ? 1 : "any"} /></label>{data.policy.fields.map((field) => <label key={field.key}>{field.label}{field.type === "boolean" || field.type === "enum" ? <select name={`value:${field.key}`} required defaultValue=""><option value="" disabled>Choose a value</option>{(field.type === "boolean" ? ["true", "false"] : field.options ?? []).map((value) => <option key={value} value={value}>{field.type === "boolean" ? value === "true" ? "Yes" : "No" : value}</option>)}</select> : <input name={`value:${field.key}`} required type="number" min={field.min} max={field.max} step={field.type === "integer" ? 1 : "any"} />}</label>)}</div><button className="button primary" type="submit">{busy ? "Receiving…" : "Submit budget request"}</button></fieldset>{message && <p role="status">{message}</p>}</form>;
}

function AllocationReview({ row, stale, busy, error, onClose, onDecide }: { row: Row; stale: boolean; busy: boolean; error: string; onClose: () => void; onDecide: (decision: "approve" | "reject", rationale: string) => Promise<void> }) {
  const ref = useRef<HTMLDialogElement>(null), [rationale, setRationale] = useState("");
  const [localError, setLocalError] = useState("");
  useEffect(() => { ref.current?.showModal(); }, []);
  const approve = row.status === "pending_approval" && row.proposed > 0 && !stale;
  return <dialog ref={ref} className="inbox-review-dialog" aria-labelledby="allocation-review-title" onCancel={(event) => { if (busy) event.preventDefault(); else onClose(); }}><form onSubmit={async (event) => { event.preventDefault(); setLocalError(""); const decision = (event.nativeEvent as SubmitEvent).submitter?.getAttribute("value"); if (decision !== "approve" && decision !== "reject") { setLocalError("Choose Approve budget or Decline request to record your decision."); return; } try { await onDecide(decision, rationale); } catch (error) { setLocalError(error instanceof Error ? error.message : "Decision could not be saved."); } }}><span className="eyebrow">Shared-budget decision</span><h2 id="allocation-review-title">{row.agent.name}</h2><h3>{row.name}</h3><p>{row.reason}</p><div className="inbox-amounts"><div><span>Requested</span><strong>{row.requested.toLocaleString()} {row.unit}</strong></div><div><span>Policy permits</span><strong>{row.proposed.toLocaleString()} {row.unit}</strong></div></div><p>{row.explanation}</p><p>Approval reserves this amount. It does not claim that work ran or that usage was measured.</p>{stale && <p className="form-error" role="alert">The portfolio changed. Close this review and inspect the latest allocation.</p>}<label>Decision rationale<textarea value={rationale} onChange={(event) => setRationale(event.target.value)} required maxLength={240} rows={3} /></label>{(error || localError) && <p className="form-error" role="alert">{localError || error}</p>}<div className="inbox-dialog-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Keep pending</button><button type="submit" name="decision" value="reject" className="button secondary" disabled={busy || stale}>Decline request</button><button type="submit" name="decision" value="approve" className="button primary" disabled={busy || !approve}>{busy ? "Saving decision…" : "Approve budget"}</button></div></form></dialog>;
}
