import { primaryResource, type FieldDefinition, type FieldValue, type WorkspaceData } from "./domain.ts";
import type { GitHubPullRequest } from "./github-server.ts";

function normalizeLabel(value: string) {
  return value.toLowerCase().replace(/[`*_]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
}

interface DeclaredField {
  label: string;
  rawLabel: string;
  value: string;
}

function markdownFields(body: string) {
  const values: DeclaredField[] = [];
  let policyIntakeSections = 0;
  let insidePolicyIntake = false;
  let fence: "`" | "~" | null = null;
  for (const rawLine of body.split(/\r?\n/)) {
    const fenceLine = /^\s*(`{3,}|~{3,})/.exec(rawLine);
    if (fenceLine) {
      const marker = fenceLine[1][0] as "`" | "~";
      if (fence === marker) fence = null;
      else if (fence === null) fence = marker;
      continue;
    }
    if (fence) continue;
    const heading = /^#{1,6}\s+(.+?)\s*#*\s*$/.exec(rawLine.trim());
    if (heading) {
      insidePolicyIntake = normalizeLabel(heading[1]) === "policy intake";
      if (insidePolicyIntake) policyIntakeSections += 1;
      continue;
    }
    if (!insidePolicyIntake) continue;
    const line = rawLine.trim().replace(/^(?:[-*+]|\d+[.)])\s+/, "").replace(/\*\*/g, "");
    const separator = line.indexOf(":");
    if (separator < 1) continue;
    const rawLabel = line.slice(0, separator).trim();
    const label = normalizeLabel(rawLabel);
    const value = line.slice(separator + 1).trim();
    if (label && value) values.push({ label, rawLabel, value });
  }
  return { values, policyIntakeSections };
}

function fieldAliases(field: FieldDefinition) {
  const aliases = new Set([normalizeLabel(field.key), normalizeLabel(field.label)]);
  // Accept only hints generated by this field's declared schema, not arbitrary
  // parenthetical text that could conceal an unknown or ambiguous field.
  const hint = field.type === "boolean" ? "yes/no" : field.type === "enum" ? field.options?.join(", ") : field.min !== undefined && field.max !== undefined ? `${field.min}–${field.max}` : undefined;
  if (hint) aliases.add(normalizeLabel(`${field.label} (${hint})`));
  const signal = `${normalizeLabel(field.key)} ${normalizeLabel(field.label)}`;
  if (signal.includes("critical")) aliases.add("business criticality");
  if (signal.includes("readiness")) aliases.add("execution readiness");
  if (signal.includes("urgency")) aliases.add("urgency");
  if (signal.includes("workflow") && signal.includes("type")) aliases.add("workflow type");
  if (signal.includes("approved") || signal.includes("approval")) aliases.add("execution approved");
  return [...aliases];
}

function fieldMatches(fields: DeclaredField[], aliases: string[]) {
  return fields.filter(({ label }) => aliases.includes(label));
}

function declaredNumber(raw: string, allowUnit: boolean) {
  const normalized = raw.trim().replace(/,/g, "");
  const pattern = allowUnit ? /^-?\d+(?:\.\d+)?(?:\s+[A-Za-z][A-Za-z0-9 _/-]*)?$/ : /^-?\d+(?:\.\d+)?$/;
  if (!pattern.test(normalized)) return null;
  const numeric = Number(normalized.match(/^-?\d+(?:\.\d+)?/)?.[0]);
  return Number.isFinite(numeric) ? numeric : null;
}

function parsedFieldValue(field: FieldDefinition, raw: string): FieldValue | null {
  if (field.type === "number" || field.type === "integer") {
    const numeric = declaredNumber(raw, Boolean(field.unit));
    if (numeric === null || field.type === "integer" && !Number.isInteger(numeric)) return null;
    if (field.min !== undefined && numeric < field.min || field.max !== undefined && numeric > field.max) return null;
    return numeric;
  }
  if (field.type === "boolean") {
    const normalized = normalizeLabel(raw);
    if (["yes", "true", "approved"].includes(normalized)) return true;
    if (["no", "false", "not approved"].includes(normalized)) return false;
    return null;
  }
  const option = field.options?.find((item) => normalizeLabel(item) === normalizeLabel(raw));
  return option ?? null;
}

function numericField(fields: DeclaredField[], aliases: string[]) {
  const matches = fieldMatches(fields, aliases);
  return { value: matches.length === 1 ? declaredNumber(matches[0].value, true) : null, duplicate: matches.length > 1 };
}

export function stableCaseId(repositoryFullName: string, number: number) {
  let hash = 2166136261;
  for (const character of repositoryFullName.toLowerCase()) { hash ^= character.charCodeAt(0); hash = Math.imul(hash, 16777619); }
  return `GH-${number}-${(hash >>> 0).toString(16).slice(0, 8)}`.slice(0, 20);
}

export function requestInputFromPullRequest(pull: GitHubPullRequest, workspace: WorkspaceData): { requestInput: Record<string, unknown> | null; errors: string[] } {
  const declared = markdownFields(pull.body);
  if (declared.policyIntakeSections === 0) return { requestInput: null, errors: ["Missing Policy intake section."] };
  if (declared.policyIntakeSections > 1) return { requestInput: null, errors: ["Multiple Policy intake sections are not allowed."] };
  const values: Record<string, FieldValue> = {};
  const errors: string[] = [];
  const fieldAliasSets = workspace.policy.fields.map((field) => fieldAliases(field));
  for (const field of workspace.policy.fields) {
    const matches = fieldMatches(declared.values, fieldAliases(field));
    if (matches.length === 0) { errors.push(`Missing ${field.label}.`); continue; }
    if (matches.length > 1) { errors.push(`Duplicate ${field.label}.`); continue; }
    const value = parsedFieldValue(field, matches[0].value);
    if (value === null) { errors.push(`Invalid ${field.label}.`); continue; }
    values[field.key] = value;
  }
  const resource = primaryResource(workspace.policy);
  const demandAliases = [normalizeLabel(`${resource.label} demand`), normalizeLabel(`requested ${resource.unit}`), "requested credits", "requested amount", "demand"];
  const minimumAliases = [normalizeLabel(`minimum useful allocation ${resource.unit}`), "minimum useful allocation", "minimum allocation", "minimum"];
  const demandResult = numericField(declared.values, demandAliases);
  const minimumResult = numericField(declared.values, minimumAliases);
  const demand = demandResult.value, minimum = minimumResult.value;
  if (demandResult.duplicate) errors.push(`Duplicate requested ${resource.unit}.`);
  else if (demand === null || demand <= 0) errors.push(`Missing or invalid requested ${resource.unit}.`);
  if (minimumResult.duplicate) errors.push("Duplicate minimum useful allocation.");
  else if (minimum === null || minimum < 0) errors.push("Missing or invalid minimum useful allocation.");
  if (!demandResult.duplicate && !minimumResult.duplicate && demand !== null && minimum !== null && minimum > demand) errors.push("Minimum useful allocation exceeds requested amount.");
  const knownAliases = new Set([...fieldAliasSets.flat(), ...demandAliases, ...minimumAliases]);
  for (const item of declared.values) if (!knownAliases.has(item.label)) errors.push(`Unknown Policy intake field: ${item.rawLabel}.`);
  if (errors.length) return { requestInput: null, errors };
  const externalId = `${pull.repositoryFullName}#${pull.number}`;
  const existing = workspace.cases.find((item) => item.source?.system === "github" && item.source.externalId.toLowerCase() === externalId.toLowerCase());
  const demands = Object.fromEntries(workspace.policy.resources.map((item) => [item.id, item.id === resource.id ? demand : 0]));
  const minimums = Object.fromEntries(workspace.policy.resources.map((item) => [item.id, item.id === resource.id ? minimum : 0]));
  return {
    requestInput: {
      case_id: existing?.id ?? stableCaseId(pull.repositoryFullName, pull.number),
      name: pull.title,
      values,
      demands,
      minimums,
      group: pull.repositoryFullName,
      source: { system: "github", external_id: externalId, url: pull.htmlUrl, imported_at: existing?.source?.importedAt ?? new Date().toISOString() },
    },
    errors: [],
  };
}

export function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`).join(",")}}`;
  return JSON.stringify(value) ?? "undefined";
}

function fingerprintMaterial(input: Record<string, unknown>) {
  const source = input.source && typeof input.source === "object" ? input.source as Record<string, unknown> : {};
  return {
    case_id: input.case_id,
    name: input.name,
    values: input.values,
    demands: input.demands,
    minimums: input.minimums,
    group: input.group,
    source: { system: source.system, external_id: source.external_id, url: source.url },
  };
}

export async function requestInputFingerprint(input: Record<string, unknown>): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonicalJson(fingerprintMaterial(input))));
  return `sha256-${[...new Uint8Array(digest)].map((value) => value.toString(16).padStart(2, "0")).join("")}`;
}
